version: 2
jobs:
  build:
    docker:
      - image: circleci/go:1.10
    steps:
      - checkout
      - run: <command>
  test:
    docker:
      - image: circleci/go:1.10
    steps:
      - checkout
      - run:
          name: Build
          command: |
            docker build -t test/helloworld:${CIRCLE_SHA1} .

      - run: Tag & Push
            - run:
          name: Tag & Push
          command: |
             docker tag quay.io/test/helloworld:${CIRCLE_SHA1} quay.io/test/helloworld:{CIRCLE_SHA1}
             docker tag quay.io/test/helloworld:${CIRCLE_SHA1} quay.io/test/helloworld:1.0
             docker push quay.io/test/helloworld:${CIRCLE_SHA1}
             docker push quay.io/test/helloworld:1.0
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
